from app import celery_app
from models import db, Booking, Trek, User
import csv
import os
from datetime import datetime, timedelta
import time

# 1. (Existing) User Async CSV Export
@celery_app.task
def export_booking_history(user_id, email):
    time.sleep(4) 
    bookings = db.session.query(Booking, Trek).join(Trek).filter(Booking.user_id == user_id).all()
    export_dir = os.path.join(os.path.dirname(__file__), '..', 'exports')
    os.makedirs(export_dir, exist_ok=True)
    filename = f"history_{user_id}_{datetime.now().strftime('%Y%m%d%H%M%S')}.csv"
    filepath = os.path.join(export_dir, filename)
    with open(filepath, mode='w', newline='', encoding='utf-8') as file:
        writer = csv.writer(file)
        writer.writerow(['Booking ID', 'Route Name', 'Location', 'Booking Date', 'Start Date', 'Status'])
        for b, t in bookings:
            b_date = b.booking_date.strftime('%Y-%m-%d') if hasattr(b, 'booking_date') and b.booking_date else 'N/A'
            t_date = t.start_date.strftime('%Y-%m-%d') if t.start_date else 'N/A'
            writer.writerow([b.id, t.name, t.location, b_date, t_date, b.status])
    return {"status": "Complete", "file": filename}


# 2. (NEW) Daily Reminder Job (Milestone 7)
@celery_app.task
def send_daily_reminders():
    """Finds treks starting tomorrow and sends reminders to participants."""
    print("--- RUNNING SCHEDULED JOB: DAILY REMINDERS ---")
    
    # Calculate tomorrow's date
    tomorrow = datetime.utcnow().date() + timedelta(days=1)
    
    # Find treks starting exactly tomorrow
    upcoming_treks = Trek.query.filter(db.func.date(Trek.start_date) == tomorrow).all()
    
    for trek in upcoming_treks:
        bookings = Booking.query.filter_by(trek_id=trek.id, status='Booked').all()
        for booking in bookings:
            user = User.query.get(booking.user_id)
            if user:
                # In a real app, this would use smtplib or a Webhook (Twilio/Sendgrid)
                print(f"[WEBHOOK SENT] To: {user.email} | Message: Reminder! Your trek '{trek.name}' starts tomorrow ({tomorrow}). Pack your gear!")
                
    return "Daily reminders processed."


# 3. (NEW) Monthly Admin Report Job (Milestone 7)
@celery_app.task
def generate_monthly_report():
    """Generates an HTML report of the last 30 days and saves/sends it to Admin."""
    print("--- RUNNING SCHEDULED JOB: MONTHLY REPORT ---")
    
    thirty_days_ago = datetime.utcnow() - timedelta(days=30)
    
    # Calculate stats
    recent_bookings = Booking.query.filter(Booking.booking_date >= thirty_days_ago).all()
    total_participants = len(recent_bookings)
    
    completed_treks = Trek.query.filter(Trek.status == 'Completed').count()
    
    # Generate HTML string
    html_content = f"""
    <html>
        <head><style>body {{ font-family: Arial; padding: 20px; }} h1 {{ color: #FF4757; }}</style></head>
        <body>
            <h1>OnTreq Monthly Activity Report</h1>
            <p><strong>Generated On:</strong> {datetime.utcnow().strftime('%Y-%m-%d')}</p>
            <hr>
            <h3>Platform Statistics (Last 30 Days)</h3>
            <ul>
                <li>Total New Bookings / Participants: <strong>{total_participants}</strong></li>
                <li>Total Treks Successfully Completed: <strong>{completed_treks}</strong></li>
            </ul>
            <p><em>* This report was auto-generated by the OnTreq Celery Beat Scheduler.</em></p>
        </body>
    </html>
    """
    
    # Save the HTML report to the exports folder
    export_dir = os.path.join(os.path.dirname(__file__), '..', 'exports')
    os.makedirs(export_dir, exist_ok=True)
    filename = f"Admin_Report_{datetime.utcnow().strftime('%b_%Y')}.html"
    filepath = os.path.join(export_dir, filename)
    
    with open(filepath, 'w', encoding='utf-8') as file:
        file.write(html_content)
        
    print(f"[EMAIL SIMULATION] Emailed Monthly HTML report to admin@ontreq.com. File saved as {filename}")
    
    return "Monthly report generated."